# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestluutin():

  options = webdriver.ChromeOptions()
  options.add_experimental_option('excludeSwitches', ['enable-logging'])
  driver = webdriver.Chrome(options=options)

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testluutin(self):
    self.driver.get("https://www.chotot.com/")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.LINK_TEXT, "Đăng nhập").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cpt13la:nth-child(2) .i1pbvj0j").send_keys("0333454717")
    self.driver.find_element(By.CSS_SELECTOR, ".cpt13la:nth-child(3) .i1pbvj0j").send_keys("@#@@!!!!!!")
    self.driver.find_element(By.CSS_SELECTOR, ".accent").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".Categories__Item-l8pxai-2:nth-child(1) .img-cat").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".WrapperScroll_wrapperOverflow__1AXEo:nth-child(3) .AdItem_item__1kT2X:nth-child(1) .commonStyle_adTitleGrid__2-G7D").click()
    time.sleep(1)
    news_found = self.driver.find_element(By.XPATH, '/html/body/div[1]/div/div[3]/div[1]/div/div[4]/div[2]/h1').text
    self.driver.find_element(By.CSS_SELECTOR, ".SaveAd_saveAdViewDetail__tDLpa > p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".i1dws2ge").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".l1t7n4kh:nth-child(6) .r13jsj5k").click()
    time.sleep(1)
    saved_news = self.driver.find_element(By.XPATH, '/html/body/div[1]/main/div[1]/div[2]/ul/div/li/a/div[2]/div/h3').text
    if saved_news == news_found:
      print("PASS")
    else:
      print("FAIL")
  
if __name__ == "__main__":
  testcase = TestTestluutin()
  testcase.test_testluutin()