# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin():

  options = webdriver.ChromeOptions()
  options.add_experimental_option('excludeSwitches', ['enable-logging'])
  driver = webdriver.Chrome(options=options)

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin(self):
    self.driver.get("https://www.chotot.com/")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.CSS_SELECTOR, "b").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cpt13la:nth-child(2) .i1pbvj0j").send_keys("0333454717")
    self.driver.find_element(By.CSS_SELECTOR, ".cpt13la:nth-child(3) .i1pbvj0j").send_keys("@#@@!!!!!!")
    self.driver.find_element(By.CSS_SELECTOR, ".accent").click()
    time.sleep(0.5)
    name = self.driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div/div[2]/div/a/span").text
    if "Duy Minh" in name:
      print("PASS")
    else:
      print("FAIL")
  
if __name__ == "__main__":
  testcase = TestTestlogin()
  testcase.test_testlogin()