# Generated by Selenium IDE
from pydoc import classname
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin():

  options = webdriver.ChromeOptions()
  options.add_experimental_option('excludeSwitches', ['enable-logging'])
  driver = webdriver.Chrome(options=options)

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin(self):
    self.driver.get("https://www.coolmate.me/")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.CSS_SELECTOR, ".header-actions__button:nth-child(2) img:nth-child(2)").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").send_keys("duyminh081201@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("4\'^:jzVZ]YvCX8f")
    self.driver.find_element(By.CSS_SELECTOR, ".login-btn").click()
    time.sleep(1.5)
    message = self.driver.find_element(By.CSS_SELECTOR, ".notify__message").text
    if message:
      print(message)
    else:
      print('FAIL')
  
if __name__ == "__main__":
  testcase = TestTestlogin()
  testcase.test_testlogin()