# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestThemhangvaogio():
  options = webdriver.ChromeOptions()
  options.add_experimental_option('excludeSwitches', ['enable-logging'])
  driver = webdriver.Chrome(options=options)
  def test_themhangvaogio(self):
    self.driver.get("https://www.coolmate.me/")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.CSS_SELECTOR, ".mobile--hidden img:nth-child(2)").click()
    self.driver.find_element(By.NAME, "keyword").send_keys("áo ba lỗ")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".product-search:nth-child(1) .product-search__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-select--tshirt_size > .m .checkmark").click()
    self.driver.find_element(By.LINK_TEXT, "Thêm vào giỏ hàng").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".header-actions__button:nth-child(3) img:nth-child(2)").click()
    time.sleep(3)
    message = self.driver.find_element(By.CSS_SELECTOR, ".notify__message").text
    if message:
      print(message)
    else: 
      print("FAIL")
    
    
if __name__ == "__main__":
  testcase = TestThemhangvaogio()
  testcase.test_themhangvaogio()
